export const theme = {
  colors: {
    bg: '#0C0C0E',
    bgCard: '#18181B',
    bgMuted: '#27272A',
    accent: '#2DD4BF',
    accentLight: 'rgba(45,212,191,0.14)',
    accentSoft: 'rgba(45,212,191,0.08)',
    text: '#E4E4E7',
    textSecondary: '#A1A1AA',
    textMuted: '#71717A',
    border: '#27272A',
    error: '#FB7185',
    destructive: '#FB7185',
    white: '#FFFFFF',
  },
  typography: {
    h1: { fontSize: 24, fontWeight: '700' as const },
    h2: { fontSize: 17, fontWeight: '600' as const },
    h3: { fontSize: 15, fontWeight: '600' as const },
    body: { fontSize: 15, fontWeight: '400' as const },
    bodySemibold: { fontSize: 15, fontWeight: '600' as const },
    caption: { fontSize: 13, fontWeight: '400' as const },
    captionSemibold: { fontSize: 13, fontWeight: '600' as const },
    small: { fontSize: 12, fontWeight: '400' as const },
    label: { fontSize: 11, fontWeight: '600' as const, textTransform: 'uppercase' as const },
  },
  shadow: {
    sm: {
      shadowColor: '#000000',
      shadowOpacity: 0.04,
      shadowRadius: 3,
      shadowOffset: { width: 0, height: 1 },
      elevation: 1,
    } as const,
    md: {
      shadowColor: '#000000',
      shadowOpacity: 0.04,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    } as const,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    full: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    screenPadding: 16,
  },
};

export type Theme = typeof theme;
